try{
    let a = adaum
}
catch(error){
    console.log(error.name)
    console.log(yello)
}
finally{
    console.log("hello")}